DROP TABLE IF EXISTS NUM9;
CREATE TABLE NUM9(
USER_ID INT PRIMARY KEY,
NAME VARCHAR(100) NOT NULL,
EMAIL VARCHAR(100) UNIQUE NOT NULL,
AGE INT CHECK(AGE>18),
REG_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

 
INSERT INTO NUM9(USER_ID,NAME,EMAIL,AGE)
VALUES(172,'KOWSHIIK','KOWSHIK90@GMAIL.COM',21),
(189,'JACKI','KOHIK34@GMAIL.COM',31),
(181,'ODYI','OWSHIK56@GMAIL.COM',42),
(140,'OGGYY','WSHIK46@GMAIL.COM',24);



SELECT * FROM NUM9;

--TO RENAME NAME COLUNM FULL_NAME
ALTER TABLE NUM9
RENAME COLUMN NAME TO FULL_NAME;

-- TO CHANGE THE AGE COLUMN DATA TYPE TO SMALLINT
ALTER TABLE NUM9
ALTER COLUMN AGE TYPE SMALLINT;

 -- TO ADD NOT NULL CONSTANT AT AGE
 ALTER TABLE NUM9
 ALTER COLUMN AGE SET NOT NULL;

 --TO CHECK  
 ALTER TABLE NUM9
 ADD CONSTRAINT AGE CHECK (AGE>=20);

 --TABLE ALTER NAME....
 ALTER TABLE NUM9
 RENAME TO KOWSHIK;
 SELECT * FROM KOWSHIK ORDER BY USER_ID ASC;