DROP TABLE IF EXISTS NUM;


CREATE TABLE NUM1(
USER_ID INT PRIMARY KEY,
NAME VARCHAR(100) NOT NULL,
EMAIL VARCHAR(100) UNIQUE NOT NULL,
AGE INT CHECK(AGE>18),
REG_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
SELECT * FROM NUM1;

INSERT INTO NUM1(USER_ID,NAME,EMAIL,AGE)
VALUES(122,'KOWSHIK','KOWSHIK@12GMAIL.COM',21);

 