SELECT * FROM PRODUCTS;

--NOW()- GET CURRENT TIME AND TIME
SELECT NOW() AS CURRENT_DATETIME


--CURENT_DATE-GET DATE
SELECT  CURRENT_DATE AS TODAY_DATE;

SELECT ADDED_DATE,CURRENT_DATE,(CURRENT_DATE-ADDED_DATE) AS DATE_DIFFERENCE
FROM PRODUCTS;


--EXTRACT()-EXTRACT PARTS OF DATE...YEAR,MONTH AND DAY FROM THE ADDED_DATE
SELECT PRODUCT_NAME,
EXTRACT(MONTH FROM ADDED_DATE) AS YEAR_ADDED,
EXTRACT(YEAR FROM ADDED_DATE) AS YEAR_ADDED
FROM PRODUCTS;


--DATE_PART()-GET SPECIFIC DATE PART
--EXTRACT THE DAY OF YHE WEEK FROM ADDED_DATE. WILL CONSIDER(0-6) IN A WEEK

SELECT PRODUCT_NAME,ADDED_DATE,
DATE_PART( 'DOW' , ADDED_DATE ) AS DAY_OF_WEEK
FROM PRODUCTS;


--AGE()- CALCULATE AGE BETWEEN DATES
--CALCULATE THE TIME DIFFERNCE BETWEEN ADDED_DATE AND TODAY'S DATE
SELECT PRODUCT_NAME ,
AGE(CURRENT_DATE,ADDED_DATE) AS AGE_SINCE_ADDED
FROM PRODUCTS;



--TO_CHAR()- FORMAT DATES AS STRINGS
--FORMATS ADDED_DATE IN A CUSTOMER FORMATE (DD-MON-YYYY). USE WEB_SEACRH FOR MORE EXTRACT  FUNCTION.

SELECT PRODUCT_NAME ,
TO_CHAR(ADDED_DATE,'DD-MON-YYYY') AS  NEW_FORMATE_DATE
FROM PRODUCTS;



-- DATE_TRUNC()- TRANCATE DATE TO PRECISION
-- TRUNCATE ADDED_DATE TO THE START OF THE MONTH,


SELECT PRODUCT_NAME,ADDED_DATE,
DATE_TRUNC('MONTH' ,ADDED_DATE) AS MONTH_STARTED,
DATE_TRUNC('WEEK' ,ADDED_DATE) AS WEEK_STARTED,
DATE_TRUNC('DAY' ,ADDED_DATE) AS DAY_STARTED,

DATE_PART('ISODOW' ,ADDED_DATE) AS  DAY_OF_WEEK

FROM PRODUCTS;


--INTERVAL- ADD OR DUBTRACT TIME INTERVALS
--ADD 6 MONTHS TO THE ADDED_DATE. THIS WILL GIVE 6 DAYS LATER DATE FROM THE STARTING POINT

SELECT PRODUCT_NAME,ADDED_DATE,
ADDED_DATE + INTERVAL '6 DAYS ' AS NEW_DATE
FROM PRODUCTS;


--CURRENT_TIME-GET CURRENT TIME
--RETRIVE ONLY THE CURRENT TIME.
SELECT  CURRENT_TIME AS MY_ACTUALL_TIME;

--TO_DATE()-CONVERT STRING TO DATE.
--CONVERT A STRING TO A DATE FORMAT.

SELECT TO_DATE('24-05-2025','DD-MM-YYYY') AS CONVERTED_DATE

