SELECT * FROM HUB2;

--USING AND
SELECT * FROM HUB2
WHERE SALARY >=56780.00 AND DEPARTMENT='cs';

--USING OR OPERATORS
SELECT * FROM HUB2
WHERE SALARY >=56780.00 OR DEPARTMENT='cs';


--USING NOT
SELECT * FROM HUB2
WHERE  NOT (DEPARTMENT='ict');