DROP TABLE IF EXISTS NUM3;
CREATE TABLE NUM3(
USER_ID INT PRIMARY KEY,
NAME VARCHAR(100) NOT NULL,
EMAIL VARCHAR(100) UNIQUE NOT NULL,
AGE INT CHECK(AGE>18),
REG_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

 
INSERT INTO NUM3(USER_ID,NAME,EMAIL,AGE)
VALUES(172,'KOWSHIIK','KOWSHIK90@GMAIL.COM',21),
(189,'JACKI','KOHIK34@GMAIL.COM',31),
(181,'ODYI','OWSHIK56@GMAIL.COM',42),
(140,'OGGYY','WSHIK46@GMAIL.COM',24);


 UPDATE NUM3
 SET AGE=29
 WHERE USER_ID=142;
--USE FOR GET A ASEDING ORDER
 SELECT * FROM NUM3 ORDER BY NAME ASC;
 -- MULTIPALE UPDATE
  UPDATE NUM3
  SET NAME='OGGYI' , USER_ID=076
  WHERE AGE >=25; 


--MULTIPAL UPDATE 
UPDATE NUM3
SET AGE=AGE+1
WHERE EMAIL ILIKE '%@GMAIL.COM';


SELECT * FROM NUM3;
-- IN OUT SHOW 8 ROWS CAUSE I WORK 2ND TIME WITH FIX DATA IN ASAME TABLE TO FIX MY 3RD UPDATE ERROR